- go/internal/indexerhandler/p2e.go
- packages/hooks/riotGame/useSquadStaking.ts
- packages/screens/RiotGame/RiotGameEnrollScreen.tsx
Add UI to unstake squad from season 1
> feat: support to unstake from Season 1

- packages/components/Pagination.tsx
- packages/components/activity/ActivityTable.tsx
Fix #470 
Needs:
Looks like this:
> Allow change pagination parameters Fix #470 [done ✅]

- packages/components/OmniLink.tsx
- packages/components/TopMenu/ConnectWalletButton.tsx
- packages/components/TopMenu/TopMenu.tsx
- packages/components/UserNameInline.tsx
- packages/components/collections/CollectionInfoInline.tsx
- packages/components/hub/ProfileButton.tsx
- packages/components/nfts/NFTView.tsx
- packages/screens/Marketplace/NFTDetailScreen.tsx
- packages/screens/UserPublicProfile/UserPublicProfileScreen.tsx
- packages/screens/WalletManager/MyNFTs.tsx
- packages/utils/setDocumentTitle.ts
Fixes #478
Demo here:
https://user-images.githubusercontent.com/322761/224984270-2a2c7a21-771a-46a9-a699-5dcc07caa308.mp4
https://user-images.githubusercontent.com/322761/225202739-a94c96fb-02e1-4450-a868-658df5ed5c51.mp4
> Allow Right click and Meta (control,command) open in a new tab [done ✅]

- packages/hooks/feed/useUpdateAvailableFreePost.ts
- packages/hooks/feed/useUpdatePostFee.ts
this is a hotfix, we should use react-query instead of callback+useState
> fix: memoize social feed query hooks

- go/cmd/teritori-indexer/main.go
- go/internal/indexerhandler/handle.go
Due to refactor social feed contract from env to network package, there was a missing part that has not been refactored.
> fix indexer  for social feed contract

- packages/components/socialFeed/NewsFeed/NewsFeed.tsx
- packages/components/socialFeed/NewsFeed/NewsFeedInput.tsx
- packages/hooks/feed/useUpdateAvailableFreePost.ts
- packages/hooks/feed/useUpdatePostFee.ts
- packages/screens/DAppStore/components/DAppStoreData.tsx
- packages/screens/FeedNewArticle/FeedNewArticleScreen.tsx
https://github.com/TERITORI/teritori-dapp/issues/522
> fix(social-feed): make less api calls

- packages/components/CollectionView.tsx
- packages/hooks/useCollectionInfo.ts
- packages/hooks/useCollections.ts
- packages/hooks/useMintEnded.ts
> fix: reduce RPCs calls by disabling refetching

- packages/components/FilePreview/VideoView.tsx
- packages/utils/style/fonts.ts
Issue:
https://github.com/TERITORI/teritori-dapp/issues/526
> fix(social feed): increase text line height and video padding

- packages/components/cards/CommentsContainer.tsx
- packages/screens/FeedPostView/FeedPostViewScreen.tsx
Fixes: https://github.com/orgs/TERITORI/projects/2/views/1?pane=issue&itemId=25401500
Test:
https://user-images.githubusercontent.com/13379067/231695320-dbb4c4c2-72b2-4ba4-9e40-845981ffb3d8.mov
> fix(social feed): refresh after posting comment

- packages/components/CollectionView.tsx
- packages/components/collections/CollectionHeader.tsx
- packages/components/collections/CollectionSocialButtons.tsx
- packages/hooks/collection/useBunkerMinterConfig.ts
- packages/hooks/collection/useBunkerMinterCurrentSupply.ts
- packages/hooks/collection/useBunkerMinterWhitelistSize.ts
- packages/hooks/collection/useCollectionThumbnailInfo.ts
- packages/hooks/collection/useEthMinterConfig.ts
- packages/hooks/collection/useEthMinterCurrentSupply.ts
- packages/hooks/collection/useEthMinterIsPaused.ts
- packages/hooks/collection/useEthMinterNFTAddress.ts
- packages/hooks/collection/useEthMinterWhitelists.ts
- packages/hooks/collection/useEthNFTContractName.ts
- packages/hooks/collection/useEthNFTContractURI.ts
- packages/hooks/riotGame/useBreeding.ts
- packages/hooks/useBreedingConfig.ts
- packages/hooks/useCollectionInfo.ts
- packages/hooks/useNFTContractInfo.ts
- packages/hooks/useNFTInfo.ts
- packages/hooks/useRemoteJSON.ts
- packages/screens/Launchpad/MintCollectionScreen.tsx
- packages/screens/Marketplace/CollectionScreen.tsx
- packages/screens/Marketplace/CollectionToolsScreen.tsx
- packages/screens/RiotGame/component/CollectionThumb.tsx
- packages/screens/RiotGame/component/CollectionView.tsx
- packages/utils/collection.ts
this reduces the number of queries used to fully render the marketplace by 20%
and for the launchpad 25%
> fix: reduce number of queries used to render collections thumbnails

- packages/components/TopMenu/TopMenu.tsx
- packages/components/TopMenu/TopMenuBox.tsx
**Before**
**After**
https://user-images.githubusercontent.com/50441633/233109477-3e98db89-845e-417f-a7a0-da9c9e5058d1.mp4
> fix: adjust automatically the TopMenu height

- packages/components/collections/CollectionHeader.tsx
The problem: https://github.com/TERITORI/teritori-dapp/issues/520 
The Fix:
https://user-images.githubusercontent.com/322761/231625871-44a2ee47-0b9c-4a25-8e2e-e7422028b129.mp4
- Visit https://deploy-preview-547--testitori.netlify.app/ or your local
- Navigate to a collection in the marketplace
- Check the header issue detailed in the video in this PR
- Review that the issue is not present anymore.
- Optional: compare production and this PR for differences.
> fix(collection screen): better render during load

- packages/screens/DAppStore/apps/toripunks/content/RussianRoulette.tsx
bugfix-Teritori issue number 7 inversion of text
> fix(toripunks dApp): results screen

- packages/components/OwnedNFTs.tsx
- packages/components/TopMenu/TopMenuLiveMint.tsx
- packages/components/carousels/CollectionsCarouselHeader.tsx
- packages/components/carousels/CollectionsCarouselSection.tsx
- packages/components/collections/CollectionGallery.tsx
- packages/hooks/useCollections.ts
- packages/screens/Marketplace/MarketplaceScreen.tsx
- packages/screens/RiotersFooter/RiotersFooterScreen.tsx
> feat: Make the Marketplace Landing page into a grid

- App.tsx
- packages/components/GovernanceBox/GovernanceBox.tsx
- packages/components/ScreenContainer/index.tsx
- packages/components/nftDetails/NFTMainInfo.tsx
- packages/screens/Swap/SwapScreen.tsx
- packages/screens/Swap/components/ConnectModal.tsx
- packages/screens/WalletManager/components/Overview.tsx
How to test:
Browse around the app and resize the browser.
I see them all fixed.
> fix: white flashes when resizing the app

- packages/components/images/AvatarWithFrame.tsx
- packages/components/socialFeed/SocialThread/DateTime.tsx
- packages/components/socialFeed/SocialThread/SocialCardHeader.tsx
- packages/utils/style/layout.ts
> fix: responsive SocialCardHeader

- assets/icons/credit-card.svg
- packages/components/navigation/BuyTokens.tsx
- packages/components/navigation/Sidebar.tsx
The Osmosis website doesn't have a buy tokens button on mobile.
https://user-images.githubusercontent.com/322761/234165433-cac4bee4-b57e-40fc-9d90-29a8391f7c24.mp4
> feat: "buy tokens" button

- go/internal/indexerhandler/feed.go
- go/pkg/quests/quests.json
- packages/components/hub/HubIntro.tsx
Screenshot:
- The deployed Netify URL can't be used
- Need the backend and indexer deployment
- Run the project in your local branch and point the backend URL to your local. https://github.com/TERITORI/teritori-dapp/blob/8fba61e64cd92e1e7829d6fa4a0fd4d0f61d39b7/packages/networks/teritori/index.ts#L22
- VIsit the Quest section of the app. And you will see the new quests.
> feat: Add new quests to social feed

- packages/context/WalletsProvider/adena.ts
> fix: adena ready state

- packages/components/inputs/SearchNSInputContainer.tsx
- packages/components/modals/SendModal.tsx
- packages/components/user/AvatarWithName.tsx
Add `SearchNSInputContainer` as a wrapper for Inputs
Usage example in `SendModal.tsx`
> feat: add search by name on address inputs

- packages/screens/DAppStore/apps/toripunks/content/ComicBookHistory.tsx
- packages/screens/DAppStore/apps/toripunks/content/ComicBooks.tsx
> fix: TORIPUNKS dapp texts

- networks.json
- packages/networks/teritori-testnet/index.ts
> fix: restore testnet backend endpoint config

- packages/components/socialFeed/NewsFeed/NewsFeedInput.tsx
Sometime fee 1_000_000 is not enough to post and I don't find a way to force this value in Adena popup
> Adjust fee to post

- packages/components/cards/NFTAttributeCard.tsx
- packages/components/cards/NFTCancelListingCard.tsx
- packages/components/cards/NFTPriceBuyCard.tsx
- packages/components/cards/NFTSellCard.tsx
- packages/components/nftDetails/NFTAttributes.tsx
- packages/components/nftDetails/NFTMainInfo.tsx
- packages/components/nftDetails/components/NFTSellInfo.tsx
- packages/components/nfts/NFTView.tsx
- packages/hooks/useNFTInfo.ts
- packages/screens/Marketplace/NFTDetailScreen.tsx
- packages/utils/types/nft.ts
Allow the user to click list nft: It will navigate to nft details
Added UI element: that allows the user to see if the marketplace is opened for the selected NFT.
Refactored: Types
> feat: menu-list-nft

- packages/components/activity/ActivityTable.tsx
- packages/components/collections/CollectionHeader.tsx
- packages/screens/Marketplace/CollectionScreen.tsx
> fix: collection screen and activity table layout

- packages/hooks/feed/useFetchFeed.ts
We wait the proper implementation of Gno feeds pagination, in the mean time we patch the code just to be able to test feeds's features
> fix: temporary patch for gno feeds

- packages/components/FilePreview/AudioView.tsx
- packages/components/FilePreview/AudioWaveform/AudioWaveform.type.ts
- packages/components/FilePreview/AudioWaveform/AudioWaveform.web.tsx
- packages/components/FilePreview/EditableAudioPreview.tsx
- packages/components/socialFeed/SocialThread/SocialMessageContent.tsx
> fix: social feed audio size fixed

- packages/components/dao/DAOSelector.tsx
- packages/components/inputs/SelectInput.tsx
- packages/components/modals/SendModal.tsx
- packages/hooks/useNSPrimaryAlias.ts
- packages/screens/TeritoriNameService/TNSManageScreen.tsx
- Use SelectInput in `DAOSelector`.
- Enhance `SelectInput` and add the possibility to enters a value to search in the `SelectInput` list (Not effective for `DAOSelector`, the image is just an example)
Before, we used `@react-native-picker/picker`
See https://github.com/TERITORI/teritori-dapp/blob/99619c93a12231e8fe551dcfa8d8cb9f84be030f/packages/components/dao/DAOSelector.tsx#L18
And https://github.com/TERITORI/teritori-dapp/blob/99619c93a12231e8fe551dcfa8d8cb9f84be030f/packages/components/inputs/SelectInput.tsx#L52
>  fix: Enhance SelectInput and DAOSelector

- packages/screens/Settings/SettingsScreen.tsx
- packages/screens/Settings/components/Notifications.tsx
- packages/screens/Settings/components/SettingItem.tsx
- packages/screens/Settings/components/commonStyles.ts
> Fix: Settings page responsive

- .github/workflows/js.yml
- Makefile
- package.json
- yarn.lock
I added ts-unused-exports library to check if we have some unused exports and so some useless components, dead code etc.
Signed-off-by: clegirar <clemntgirard@gmail.com>
> chore: add ts-unused-exports library

- packages/components/NetworkSelector/NetworkSelectorMenu.tsx
- packages/components/NetworkSelector/NetworkSelectorMobile.tsx
- packages/components/modals/NetworksListModal.tsx
> fix: responsive networks modal

- packages/components/BrandText/BrandTextBase.tsx
- packages/hooks/useTheme.ts
- packages/screens/Settings/SettingsScreen.tsx
- packages/store/slices/settings.ts
- packages/store/store.ts
- packages/utils/themes.ts
Add light theme logic and a little example on how use it 👍
> feat: theming foundations

- webpack.config.js
axios is not properly resolved and is used by the gno client
this fixes it and probably other problems with cjs libs
for example gno dao list is not working without this fix
> fix: cjs deps are not properly loaded

- .github/workflows/js.yml
- README.md
- package.json
Reason: https://nodejs.org/en/blog/announcements/nodejs16-eol/
> chore(package): update node version to v18.1.0

- packages/components/TopMenu/TopMenuMyTeritories.tsx
- packages/components/TopMenu/TopMenuMyWallets.tsx
Fixed, it now goes to Swap.
Fixed: is not coming soon, but it shows the current existing daos.
> feat(top-menu-integrations): Add 'Swap' and Orgs into TopMenuMyWallet

- web/index.html
the file was generated using `npx expo customize web/index.html`
and this style was modified 
```css
html,
body,
#root {
width: 100%;
/* To smooth any scrolling behavior */
-webkit-overflow-scrolling: touch;
margin: 0px;
padding: 0px;
/* Allows content to fill the viewport and go beyond the bottom */
min-height: 100%;
}
```
to add `background-color: black;`
> fix: put black background in html

- packages/screens/Marketplace/CollectionScreen.tsx
> feat(Marketplace): Clean up NFT collection names

- packages/components/images/AvatarWithFrame.tsx
- packages/components/mediaPlayer/MediaNameImage.tsx
- packages/components/mediaPlayer/MediaPlayerVideo.tsx
- packages/components/music/MusicList.tsx
- packages/components/nfts/NFTs.tsx
- packages/components/socialFeed/NewsFeed/NewsFeed.tsx
- packages/components/socialFeed/SocialCard/cards/SocialVideoCard.tsx
- packages/components/video/VideoCard.tsx
- packages/components/video/VideosList.tsx
- packages/context/MediaPlayerProvider.tsx
- packages/screens/FeedPostView/FeedPostViewScreen.tsx
- packages/screens/FeedPostView/components/FeedPostDefaultView.tsx
- packages/screens/FeedPostView/components/FeedPostVideoView.tsx
- packages/screens/FeedPostView/components/VideoComment.tsx
- packages/utils/social-feed.ts
> feat: video details

- packages/components/navigation/components/BackButton.tsx
- packages/context/MessageProvider.tsx
- packages/screens/Message/MessageScreen.tsx
- packages/screens/Message/components/ChatHeader.tsx
- packages/screens/Message/components/ChatItem.tsx
- packages/screens/Message/components/ChatSection.tsx
- packages/screens/Message/components/Friends.tsx
- packages/screens/Message/components/FriendsBar.tsx
- packages/screens/Message/components/FriendshipManager.tsx
- packages/screens/Message/components/SideBarChats.tsx
https://github.com/TERITORI/teritori-dapp/assets/13379067/5c0df514-e6ea-4be2-b97a-4abb90a8e3cf
> feat: message screen responsive

- packages/components/socialFeed/SocialCard/cards/SocialArticleCard.tsx
- packages/screens/DAppStore/components/DAppBox.tsx
- packages/store/slices/dapps-store.ts
https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization
> feat(sidebar): reduce re-render

- packages/components/socialFeed/NewsFeed/NewsFeed.type.ts
- packages/components/socialFeed/NewsFeed/NewsFeedInput.tsx
- packages/components/socialFeed/NewsFeed/NewsFeedQueries.ts
- packages/components/socialFeed/SocialCard/ArticleRenderer.tsx
- packages/components/socialFeed/SocialCard/SocialMessageContent.tsx
- packages/components/socialFeed/SocialCard/cards/SocialCommentCard.tsx
- packages/components/socialFeed/SocialCard/cards/SocialThreadCard.tsx
- packages/hooks/feed/useFetchComments.ts
- packages/networks/index.ts
- packages/screens/FeedNewArticle/FeedNewArticleScreen.tsx
- packages/utils/transactions/getTxInfo.tsx
The `shortDescription` and `thumbnailImage` wasn't send at Article creation.
Now
> fix: articles thumbnail and short description

- packages/screens/UserPublicProfile/tabScreens/VideosUPPScreen.tsx
> fix: use the correct videos list in UPP

- packages/screens/Feed/components/MusicFeed.tsx
- packages/screens/Feed/components/VideosFeed.tsx
this is a hotfix, we need to find a way to have a stable layout without all this complexity
> fix: feed music and video layout hotfix

- packages/screens/UserPublicProfile/components/UPPScreenContentWrapper.tsx
hotfix for upp layout, we need to find a way to have a stable upp layout without this much complexity
> fix: remove footer in upp

- babel.config.js
- networks.json
- package.json
- packages/components/collapsable/CollapsableSection.tsx
- packages/hooks/useNFTInfo.ts
- packages/networks/teritori-testnet/index.ts
- yarn.lock
fix several marketplace bugs
- most important is that you can't buy list or sell nft because there is a crash in react-native-reanimated, this uses a plain view as temporary fix
- don't require that the riot breeding contract is defined to load nfts infos
- add testnet riot to secondaryDuringMint list
- add babel plugin required by react-native-reanimated
> fix: marketplace

- .github/workflows/desktop-build.yml
- .github/workflows/mobile-build-android.yml
- .github/workflows/mobile-build-ios.yml
copied from https://github.com/berty/berty/blob/8ea882f53a6bbc68977c0c4b2369f6b90254cfbd/.github/workflows/cancel.yml
thanks @aeddi
> chore: cancel obsolete heavy CI jobs

- packages/screens/UserPublicProfile/components/UPPIntro.tsx
> fix: Premium Sub button size issue fixed

- packages/components/navigation/NormalModeNavigator.tsx
- packages/screens/LeaderboardMarketplaceScreen/LeaderboardMarketplaceScreen.tsx
- packages/screens/LeaderboardMarketplaceScreen/component/LeaderboardMarketplaceTable.tsx
- packages/utils/navigation.ts
> feat: marketplace leaderboard

- packages/components/navigation/MiniModeNavigator.tsx
- packages/hooks/useAppMode.ts
- packages/hooks/useChatActivated.ts
- packages/hooks/useOnboardStatus.ts
- packages/screens/Mini/StartScreens/ChatActivationScreen.tsx
- packages/screens/Mini/StartScreens/ModeSelectionScreen.tsx
- packages/store/slices/settings.ts
- packages/utils/navigation.ts
Show onboarding screen only once
Added the continue button in the mode selection screen
useOnboardingStatus hook created to handle whether to show the onboarding screen or not
> fix: onboarding mode selection

- packages/components/Dropdown.tsx
- packages/components/Menu.tsx
- packages/components/Pagination.tsx
- packages/components/boxes/Box.tsx
- packages/components/boxes/LegacySecondaryBox.tsx
- packages/components/buttons/IconButton.tsx
- packages/components/buttons/SocialButton.tsx
- packages/components/buttons/SocialButtonSecondary.tsx
- packages/components/buttons/ToggleableButton.tsx
- packages/components/riotersFooter/NftAdjustments.tsx
- packages/components/socialFeed/NewsFeed/NewsFeedInput.tsx
- packages/screens/DAppStore/components/Dropdown.tsx
- packages/utils/style/buttons.ts
This reverts commit 4b3b86337a0f7aaa45f86f77021595dc01fa5523.
> fix: Revert "chore: first replace of legacies boxes (#897)"

- packages/screens/Wallet/Screens/NativeWallet.tsx
Before:
A new fresh user could click on continue, but now it can't :)
> feat(wallet): Add Onboarding Checks

- packages/screens/Mini/Profile/Account.tsx
- packages/screens/Mini/Profile/AccountDetailsScreen.tsx
- packages/screens/Mini/Profile/ProfileScreen.tsx
- packages/screens/Mini/Wallet/DepositTORIScreen.tsx
- packages/screens/Mini/Wallet/TokenScreen.tsx
- packages/screens/Mini/Wallet/TransactionDetailScreen.tsx
- packages/screens/Mini/Wallet/components/ManageToken.tsx
- packages/screens/Mini/Wallet/components/ShowWalletQR.tsx
- packages/screens/Wallet/Screens/CreateWalletScreen.tsx
- packages/screens/Wallet/Screens/ImportWallet.tsx
- packages/store/slices/wallets.ts
> feat(wallet): account-rename

- packages/screens/Mini/Feed/components/PostActions.tsx
added emoji  reactions and shown top 4 emoji with count
> feat(mini-mode): Emoji reactions on mini feeds

- go/cmd/teritori-indexer/main.go
this gives an eta on cosmos indexer replay
> feat: indexer sync stats

- packages/components/navigation/getMiniModeScreens.tsx
- packages/screens/Mini/Feed/MiniCreatePostScreen.tsx
- packages/screens/Mini/components/MiniCommentInput/CommentTextInput.tsx
- packages/screens/Mini/components/MiniCommentInput/index.tsx
- packages/screens/Mini/layout/BlurScreenContainer.tsx
Replaced create post input from normal mode to mini input for creating post
> feat: mini create post

- packages/context/MediaPlayerProvider.tsx
> fix: sound in audio and video play in silent mode

- packages/components/teritoriNameService/NameNFT.tsx
- packages/screens/TeritoriNameService/TNSBurnNameScreen.tsx
- packages/screens/TeritoriNameService/TNSConsultNameScreen.tsx
- packages/screens/TeritoriNameService/TNSManageScreen.tsx
> fix: manage name, burn name and NameNFT component

- packages/screens/Mini/Profile/AddAccountScreen.tsx
- packages/screens/Wallet/Screens/NativeWallet.tsx
> fix: hide connect ledger from  NativeWallet and add account screen

- packages/screens/Mini/layout/MultiStepScreenContainer.tsx
- packages/screens/Wallet/Screens/ImportWallet.tsx
> fix: removed position absolute and used flex instead

- packages/screens/Mini/Chat/MiniAddFriendScreen.tsx
> fix: submit add Friend from keyboard

- packages/screens/Mini/Wallet/TokenScreen.tsx
fixes https://github.com/TERITORI/teritori-dapp/issues/1050
> fix(wallet): misleading UI in Token Screen

- packages/components/music/TrackCard.tsx
- packages/components/music/TrackOptionsButton.tsx
- packages/components/socialFeed/SocialActions/ShareButton.tsx
- packages/components/socialFeed/SocialActions/TipButton.tsx
> feat: added share and tip option on music list three dot button

- metro.config.js
- packages/components/Link/Link.tsx
- packages/components/Link/types.ts
- packages/components/hub/HubLanding.tsx
> fix: home banner mobile layout

- packages/screens/Mini/DAppStore/component/DAppsList.tsx
- packages/store/slices/dapps-store.ts
> feat(mini-mode): remove external and osmosis apps

- packages/components/teritoriNameService/FindAName.tsx
- packages/screens/TeritoriNameService/TNSExploreScreen.tsx
- packages/screens/TeritoriNameService/TNSMintNameScreen.tsx
- packages/screens/TeritoriNameService/TNSRegisterScreen.tsx
> fix: name service register width in mobile

- Root.tsx
- packages/screens/DAppStore/query/getFromFile.ts
- packages/screens/Mini/DAppStore/component/DAppsList.tsx
- packages/store/slices/dapps-store.ts
> feat(Mobile): normal mode hide unsupported apps (sidebar and dapp store) #1089

- CONTRIBUTING.md
first draft written by chatgpt with guidance
[EDIT] I reduced a lot, you can see original version here https://github.com/TERITORI/teritori-dapp/pull/1137/commits/c5271cf8920bf3f90ebac4ad78ac0ea6b66e16ac
tell me if you think sections from this should be added back
> chore: add web2 to web3 section in CONTRIBUTING.md

- app.config.js
- packages/context/MediaPlayerProvider.tsx
> feat: play audio on background in app

- packages/screens/Mini/Profile/ShareContactQRModal.tsx
- packages/screens/Mini/components/MobileModal.tsx
> fix: my contact QR modal UI overlap

- packages/screens/Governance/GovernanceProposal/GovernanceVoteDetails/components/VoteDetails.tsx
governance details ui glitch is fixed.
> fix: governance details ui glitch

- packages/components/modals/ModalBase.tsx
issue with close icon button, behave looks like static button, button there is onPress click event already present but no any action are there.
issue resolved.
> fix: upload video modal close icon bug fix

- packages/components/sorts/SearchInputRounded.tsx
- packages/screens/Governance/GovernanceScreen.tsx
- packages/screens/Governance/components/dropdowns/StatesDropdown.tsx
On mobile application side,  governance screen ui is break.
issue resolved, Thanks.
> fix: governance screen ui in mobile view

- networks.json
- packages/networks/index.ts
- packages/networks/saga/index.ts
upgrading the chain registry breaks the ios build so adding saga manually here
> feat: add saga mainnet

- packages/components/footers/LegalFooter.tsx
fixed the issue of static data for year in footer
> fix: issue of static date for year in footer

- packages/screens/Governance/GovernanceProposal/GovernanceDescription/GovernanceDescription.tsx
- packages/screens/Governance/GovernanceProposal/GovernanceVoteDetails/components/ChartText.tsx
- packages/screens/Governance/GovernanceProposal/GovernanceVoteDetails/components/VoteChart.tsx
- packages/screens/Governance/GovernanceProposal/GovernanceVoteDetails/components/VoteDetails.tsx
- packages/screens/Governance/GovernanceProposal/GovernanceVoteDetails/components/VoteDetailsBox.tsx
- packages/screens/Governance/GovernanceProposal/GovernanceVoteHeader/components/VoteTimeDetailsBox.tsx
fix the issue of the Governance Proposal ScreenUI break in mobile and web.
> fix: Governance Proposal Screen ui break in mobile and web

- .yarn/patches/graphql-request-npm-5.2.0-31dd65ab47.patch
- package.json
- packages/components/activity/ActivityTable.tsx
- packages/components/loaders/AnimatedLoader.tsx
- packages/components/table/TableRow.tsx
- packages/hooks/useValidators.ts
- packages/screens/AdministrationDashboard/component/ApplicationTable.tsx
- packages/screens/AllProjectAdministrationDash/component/AllApplicationTable.tsx
- packages/screens/LaunchpadApplications/component/LaunchpadApplicationsTable.tsx
- packages/screens/Marketplace/MarketplaceScreen.tsx
- packages/screens/MarketplaceLeaderboardScreen/component/MarketplaceLeaderboardTable.tsx
- packages/screens/ReadyLaunchpadApplications/component/ReadyLaunchApplicationTable.tsx
- packages/screens/Stake/components/ValidatorsList.tsx
- packages/utils/types/staking.ts
- yarn.lock
> feat(staking): service score

- packages/components/tabs/Tabs.tsx
- packages/screens/Stake/StakeScreen.tsx
> feat(staking): add "My Delegations" tab

- Makefile
- gno/r/cockpit/gno.mod
- gno/r/cockpit/render.gno
> feat: gno cockpit init

- packages/components/inputs/DateTimeInput.tsx
- packages/screens/Launchpad/components/LaunchpadAdditional.tsx
- packages/utils/errors.ts
Example here: https://github.com/TERITORI/teritori-dapp/blob/feat-datetime-input/packages/screens/Launchpad/components/LaunchpadAdditional.tsx#L107-L118
> feat: add DateTimeInput

- packages/components/socialFeed/NewsFeed/NewsFeedInput.tsx
- packages/utils/ipfs.ts
> fix: change ipfs gateway

- packages/components/socialFeed/SocialActions/TipModal.tsx
Fixes this issue: https://github.com/TERITORI/teritori-dapp/issues/1290
> fix: closing TipModal shows an error

- go/internal/indexerhandler/feed.go
- go/pkg/feed/service.go
the cache in current state incurs a big feedback delay on user side
> fix(feed): remove location cache

- assets/icons/info.svg
- packages/screens/Swap/components/SwapView/SwapSettings.tsx
I also replaced some LegacyTertiaryBox
> feat(launchpad): make a svg color dynamic

- .github/workflows/lint-pr-title.yml
> chore(ci): check pr titles

- packages/components/footers/Footer.tsx
> fix: remove box around footer social buttons

- packages/components/ScreenContainer/index.tsx
- packages/components/socialFeed/EmojiSelector.tsx
- packages/components/socialFeed/GIFSelector.tsx
- packages/components/socialFeed/NewsFeed/CreateShortPost/CreateShortPostButton.tsx
- packages/components/socialFeed/NewsFeed/RefreshButton/RefreshButton.tsx
- packages/components/socialFeed/NewsFeed/RefreshButton/RefreshButtonRound.tsx
I removed some deprecated `StyleSheet` usages
> chore(feed): Remove deprecated Stylesheet.create usages

- packages/screens/FeedPostView/components/FeedPostDefaultView.tsx
Remove unused useEffect from FeedPostDefaultView screen
Fixes #1350
> fix: removed unused effect

- apps/gnotribe/App.tsx
- apps/teritori/App.tsx
- packages/components/navigation/Navigator.tsx
- packages/components/navigation/getNormalModeScreens.tsx
- packages/components/navigation/platformSpecific.tsx
- packages/components/navigation/platformSpecific.web.tsx
- packages/components/navigation/util.tsx
- packages/context/AppConfigProvider.tsx
- packages/screens/Governance/GovernanceProposal/GovernanceProposalScreen.tsx
- packages/screens/Marketplace/NFTDetailScreen.tsx
- packages/screens/UserPublicProfile/UserPublicProfileScreen.tsx
> feat: per-app browser tabs prefix

- .eslintrc.js
- packages/components/NetworkSelector/NetworkSelectorMenu.tsx
also removes a space outside of text component
> fix: prevent unexpected fallthrough

- packages/components/socialFeed/RichText/RichText.tsx
- packages/components/socialFeed/RichText/RichText.type.ts
- packages/components/socialFeed/RichText/RichText.web.tsx
- packages/screens/FeedNewArticle/FeedNewArticleScreen.tsx
When you have a wallet connected that is member of DAOs, you can select a DAO to post with
> feat: allow to make article proposal

- packages/components/inputs/TextInputCustom.tsx
- packages/components/modals/ModalBase.tsx
- packages/components/music/FeedMusicList.tsx
- packages/components/music/TrackCard.tsx
- packages/components/music/TrackOptionsButton.tsx
- packages/components/music/UploadMusicButton.tsx
- packages/components/music/UploadMusicModal/UploadTrack.tsx
- packages/components/socialFeed/FeedFeeText.tsx
- packages/utils/style/fonts.ts
Change the `fontWeight` in music feed screen
---
Before:
After:
> fix: font weight in music feed screen

- cypress/e2e/gno/lib.ts
- increase timeout to find connect test wallet
- add should exist to retry until it find or timeout
> chore: fix CI e2e test

- gno/p/dao_core/dao_core.gno
- gno/p/dao_core/dao_core_test.gno
- gno/p/dao_interfaces/core.gno
- gno/p/dao_interfaces/core_testing.gno
- gno/p/dao_interfaces/modules.gno
- gno/p/dao_proposal_single/dao_proposal_single.gno
- gno/p/dao_roles_group/roles_group.gno
- gno/p/dao_roles_voting_group/roles_voting_group.gno
- gno/p/dao_roles_voting_group/roles_voting_group_test.gno
- gno/p/havl/havl.gno
- gno/r/dao_realm/dao_realm.gno
- gno/r/dao_roles_realm.gno/dao_roles_realm.gno
- networks.json
- packages/hooks/dao/useDAOMembers.ts
- packages/networks/gno-portal/index.ts
- packages/scripts/generateDAOSource.ts
- packages/utils/gnodao/generateMembershipDAOSource.ts
- packages/utils/gnodao/generateRolesDAOSource.ts
- remove the concept of roles from the dao core interfaces
- remove `GetMembersJSON` on the dao core
- add `getMembersJSON` on dao instance realms
- adapt dao source gen
- add `generateDAOSource` script to debug dao source generation
> feat: leaner dao interfaces

- .github/workflows/desktop-build.yml
- .github/workflows/mobile-build-android.yml
- .github/workflows/mobile-build-ios.yml
upload-artifact: 
https://github.com/TERITORI/teritori-dapp/actions/runs/13163113075/job/36736588553?pr=1477 
download-artifact: 
https://github.com/TERITORI/teritori-dapp/actions/runs/13163523128/job/36739590851?pr=1499
> fix(CI): upgrade deprecated actions/cache
