- go/internal/ethereum/ethereum.go
Only make 2 queries to filter owner/seller when owner is provided. If not then make just one query.
> fix(ethereum-backend): doubled nfts

- go/internal/indexerdb/collection.go
`max_supply` and `paused` are used in collections query without indexes
```
... where c.paused = false and c.max_supply != -1 and (select count from count_by_collection where collection_id = c.id) != c.max_supply
```
> fix: add needed index to collection

- packages/utils/backend.ts
fix #556 
- I also tried to fix it via golang at gorilla (the lib) level.
- I also tried setting different values in the backend for the gRPC, but this is the only reliable way, I found, to do it.
- Open the website in Safari (mobile and desktop).
- The sidebar and everything else should *NOW* work.
- Test other browsers for regressions.
- Needs this line commented out https://github.com/TERITORI/teritori-dapp/blob/8fba61e64cd92e1e7829d6fa4a0fd4d0f61d39b7/packages/context/SidebarProvider.tsx#L73 (addressed at #535 )
- I didn't try to send any tx using keplr.
> fix: use grpc-web default transport for safari support

- .env
- mainnet.env
- packages/components/CollectionView.tsx
- packages/components/ImageWithTextInsert.tsx
- packages/components/OptimizedImage.tsx
- packages/components/collections/CollectionInfoInline.tsx
This is a placeholder with a demo and documentation on how to set up the proxy in our infrastructure.
Guide:
https://www.digitalocean.com/community/tutorials/how-to-serve-next-generation-images-with-imgproxy-using-docker
This is what I did to set it up locally (for testing, just for now).
```
docker pull darthsim/imgproxy:latest
Run it like this
docker run --env IMGPROXY_ENABLE_WEBP_DETECTION=true  -p 8080:8080 -it darthsim/imgproxy
```
I want to set up this properly on the cloud ☁️ that we have.
We can think of some suitable parameters.
The example provided used the value of the image and how big it is actually rendered by the browser to find a good initial step.
> feat: use resizing image proxy for nfts and collections

- go/cmd/p2e-update-leaderboard/main.go
- go/pkg/p2e/rewardutil.go
- go/pkg/p2e/service.go
Description:
Currently, we reset the leaderboard at 23h59 so when user unstake between 23h59 - 00h00, his score will be taken into account in leaderboard which is unexpected behaviour.
Fix:
Now we reset leaderboard at 00h00, so all the calculation should be correct.
> fix: optimize leaderboard reset time to avoid corrupted staking situation

- packages/components/fileUploader/FileUploader.tsx
- packages/components/fileUploader/FileUploader.type.ts
- packages/components/fileUploader/FileUploader.web.tsx
- packages/components/socialFeed/SocialThread/ArticleRenderer.tsx
- packages/screens/FeedNewArticle/FeedNewArticleScreen.tsx
- packages/utils/social-feed.ts
At the article creation, the cover image is now at the same format as the articles in the feed.
It prevent the misunderstanding "Why my image is not shown as in the creation (`/feed/new`)" ?
> fix: cover image format at article creation

- packages/components/ImageWithTextInsert.tsx
- packages/components/collections/CollectionHeader.tsx
- packages/components/dao/DAOsList.tsx
- packages/components/nfts/NFTView.tsx
- packages/components/nfts/NFTs.tsx
- packages/hooks/useCollectionStats.ts
This makes the DAO lists and NFTs lists a lot more sexy on any screen width
> fix: better align dao and nft list + better nft list loading behavior

- Makefile
Either the new version of docker or the new golang images won't build with `--platform amd64` but instead require `--platform linux/amd64`
> fix(docker): explicit platform spec

- packages/components/collections/CollectionContent.tsx
- packages/components/nfts/NFTView.tsx
- packages/components/nfts/NFTs.tsx
Before this, scrolling the nfts list in collection screen can freeze a bit on my computer, with that it's smoooooth
this is not very scientific but the difference seems obvious
It memoize the NFTView and memoize it's style prop to make sure it doesn't get rerendered
Also it increase the onEndReachedThreshold and always fetch 100 nfts at a time
> fix: optimize nfts list by memoizing NFTView

- packages/components/hub/HubLanding.tsx
The Airdrop DAppCard was previously linking to "https://teritori.com/airdrop". Which is finished
> feat(hub): remove Airdrop DAppCard on HubLanding component (main)

- packages/components/tabs/Tabs.tsx
The issue was when we click on a tab, the tabs stays to the first item.
Before :
After :
> fix(tabs): scroll to the selected tab item to let it always visible

- App.tsx
- packages/store/store.ts
Woops, I missed that the `persistStore` call was needed to enable persistence in the unused exports PR, my bad
> fix: store persist

- packages/components/navigation/BuyTokens.tsx
- packages/components/navigation/Sidebar.tsx
- packages/components/navigation/SidebarMobile.tsx
This is a suggestion, there are 2 changes.
1- Since Osmosis got rid of "frontier", we got a much worse user experience to onboard users. Specially buying their first tori.
This proposed change is leveraging the existing Swap feature, so people can use our UI to swap in osmosis.
2- when the users click on the + on the sidebar it will go to dapp store instead of showing coming soon
> feat(sidebar): make "buy tokens" redirect to swap screen and enable "+" button

- packages/components/socialFeed/SocialThread/SocialMessageContent.tsx
the front assumes the feed metadata has a particular shape, but it's not guaranteed, this fix the current bug but the proper fix is to sanitize metadata with something like zod
> fix: don't crash if social feed post has bad shape

- go/cmd/feed-clean-pinata-keys/Dockerfile
- go/cmd/multisig-backend/Dockerfile
- go/cmd/p2e-update-leaderboard/Dockerfile
- go/cmd/prices-ohlc-refresh/Dockerfile
- go/cmd/prices-service/Dockerfile
- go/cmd/teritori-dapp-backend/Dockerfile
- go/cmd/teritori-indexer/Dockerfile
we can't build the dockers image since some pakage upgrade that probably happened in wesh PRs requires go >= 1.19
> fix: upgrade docker go version

- packages/screens/DAppStore/apps/toripunks/HomeScreen.tsx
- packages/screens/DAppStore/apps/toripunks/content/Content.tsx
this is a hotfix to still display the toripunk app if fonts do not load
now we need to understand why font loading fails
> fix: toripunks dapp

- go/pkg/feed/service.go
- Fixed query parameter name from "created_by" to "author_id" in the feed service.go file.
- This fixes an issue where the wrong query parameter was being used.
- The issue number is hotfix/profile-posts-not-working.
> fix(feed): fix query in user feed

- packages/components/socialFeed/SocialCard/SocialMessageContent.tsx
> fix: add default image for Post Audio

- packages/components/socialFeed/NewsFeed/NewsFeed.tsx
To test : 
- Go here : https://app.teritori.com/feed
- Write something in the input 
- Resize the browser window and see the written text disappears
---
> fix: prevent feed input from disappearing when resizing the window

- .github/workflows/js.yml
- Makefile
- package.json
with this we can run most of the js checks locally in a single command with `make lint.js` (aka `yarn && yarn lint`)
only non-destructive checks are ran
> chore: easier local js lint

- packages/screens/Mini/Chat/MiniFriendScreen.tsx
- packages/screens/Mini/Chat/NewConversationScreen.tsx
- packages/screens/Mini/Chat/NewGroupScreen.tsx
- packages/screens/Mini/Conversation/ChatInput.tsx
> fix: don't crop text in mini mode inputs

- packages/screens/Mini/Wallet/SendingToriScreen.tsx
- packages/screens/Mini/components/MiniTextInputWithDropdown.tsx
- In SendingToriScreen, fix the gas estimation by adding 100,000 to the estimated gas value.
- Update the button title in SendingToriScreen to "Sending" when the transaction is in process.
- Set the isInProcess state to true when the transaction is being signed and broadcasted.
> fix(native-wallet): gas estimation adjustment and button title

- package.json
- yarn.lock
The expo version currently used ask for a minimum of 5.3.0
> chore(deps): update typescript to version 5.3.0 in package.json

- .github/workflows/mobile-build-android.yml
- .github/workflows/mobile-build-ios.yml
- Makefile
- app.config.js
- eas.json
- packages/scripts/app-build/bumpBuildNumber.ts
Done:
- config between Google Play Console, Google Cloud, and Expo has been done
- env set for Google service account
- eas submit is submitting to the expo.dev
- expo.dev uploads to Google Play Console
The app is submitted to the Play Store for internal testing as a draft app
So, it will not be released for testing; has to be manually released from Google Play Console.
`[!] Google Api Error: Invalid request - Only releases with status draft may be created on the draft app.`
It will be automatically released for internal testing once we make the app production; for that, we should release the app to general users once. 
On latest commit: It is configured the submit only after merging to main
To check the eas submit: https://github.com/TERITORI/teritori-dapp/actions/runs/7886701324/job/2152 …
> feat: android eas submit

- packages/screens/Mini/layout/BlurScreenContainer.tsx
- packages/screens/Mini/layout/MultiStepScreenContainer.tsx
- packages/screens/Wallet/Screens/ImportWallet.tsx
1. hiding keyboard on clicking on screen other than input by wrapping component by ScrollView with scroll disabled, 
2. added focus on input while clicking on seed input container on Import seed screen
> fix: dismiss keyboard on MutiStepScreenContainer and BlurScreenContainer

- packages/screens/Mini/DAppStore/DAppStoreScreen.tsx
- packages/screens/Mini/layout/BlurScreenContainer.tsx
> fix: title not showing and extra bottom margin on dApp store screen for android 

- packages/screens/Governance/GovernanceProposal/GovernanceProposalScreen.tsx
governance details page title issue fixed by setting the title of the metadata by using navigation.setOptions in GovernanceProposalScreen.
> fix: governance details page title

- packages/screens/FeedPostView/components/FeedPostDefaultView.tsx
fixed the issue of the header label width of author name in FeedPostDefaultView
> fix: ellipsize FeedPostView header label

- .github/workflows/mobile-build-ios.yml
- app.config.js
- packages/scripts/app-build/createPrivacyInfo.ts
- packages/scripts/app-build/fixGitignore.ts
Issue detail: https://github.com/expo/expo/issues/27796
Fixed issue on Expo SDK 50: https://github.com/expo/expo/pull/28153
we can try with it for now.
> fix: ios privacy manifest

- packages/screens/Governance/GovernanceScreen.tsx
It doesn't display the Proposals that have no title
> hotfix: Prevent error on GovernanceScreen

- .github/workflows/mobile-build-android.yml
- .github/workflows/mobile-build-ios.yml
- Makefile
- weshd/go.mod
- Used go 1.20 for ./weshd only
- go 1.20 is used for mobile builds GitHub actions (android and ios)
> fix: mobile ci

- networks.json
- packages/networks/teritori-testnet/index.ts
- packages/scripts/network-setup/deploy.ts
- packages/scripts/network-setup/deployDA0DA0.ts
- packages/scripts/network-setup/deployLib.ts
- packages/scripts/network-setup/restoreContract.ts
Can now execute `deployDA0DA0.ts` with these args:
- `network-id` (required)
- `wallet` (required)
- `--keyring-backend` (optionnal)
https://github.com/TERITORI/teritori-dapp/pull/1234/files#diff-75c9ee642dbd4a76e719d9c6bb35e840757a47dad676728fe0bf383284c11177R197-R216
Can now specify `--keyringBackend` when calling `instantiateContract`
https://github.com/TERITORI/teritori-dapp/pull/1234/files#diff-75c9ee642dbd4a76e719d9c6bb35e840757a47dad676728fe0bf383284c11177R159
Better cross-plateform `home`
https://github.com/TERITORI/teritori-dapp/pull/1234/files#diff-a844341e6901a2d16b286101bec6bb725e1f5b5cfb98fff16edca1759fb10695R15
I used this to deploy DAO stuff on teritori-testnet:
`npx tsx teritori-dapp/packages/scripts/network-setup/deployDA0DA0.ts teritori-testnet wallet …
> feat(deploy-scripts): args for deployDA0DA0 + cross-platform home + deploy DA0DA0 on testnet

- packages/utils/feed/queries.ts
Posts with GIFs get now the `PostCategory` `Picture`, and are visible in Pics Feed
Users can make posts with only GIFs and no text, as with images files. So, it makes sense to treat these two case as same `PostCategory`
---
Also, I need that for the Map Feed, to correctly display the GIFs as `Picture` posts on the map. 
If not, the posts with GIFs will appear as `Normal` posts with empty content (Because the text is not mandatory)
> feat: mark gifs as PostCategory.Picture

- packages/components/table/TableWrapper.tsx
- packages/screens/LaunchpadERC20/component/LaunchpadERC20AirdropsTable.tsx
- packages/screens/LaunchpadERC20/component/LaunchpadERC20SalesTable.tsx
- packages/screens/LaunchpadERC20/component/LaunchpadERC20TokensTable.tsx
- packages/screens/MarketplaceLeaderboardScreen/component/MarketplaceLeaderboardTable.tsx
It allows to use `TableWrapper` without `paginationProps` that is useless if `showPagination` is not used.
So I also removed useless `paginationProps` usages
> fix: set a prop as optional and remove usage

- packages/screens/Launchpad/MintCollectionScreen.tsx
- packages/utils/style/layout.ts
In this PR, I use the new layout variable in a random component. I also replace all margin and padding layout values.
It looks like pretty useless, but all my small PRs are made to relieve the big NFT Launchpad one (https://github.com/TERITORI/teritori-dapp/pull/1024/files)
I'm not refactoring
> feat(launchpad): add a spacing value

- packages/components/socialFeed/RichText/RichText.web.tsx
Actually, when the user clicks on "Type message here", it does nothing.
It's just a placeholder, so we expect that focuses the editor, and lets the user type.
This weird behavior is due to the fact `placheloder` from `draft-js` `Editor` is a `div`
So I added a `TouchableWithoutFeedback` that focuses the `Editor` when `onPress`
> fix(feed): Allow to focus Article Editor by clicking the placeholder

- packages/components/socialFeed/SocialActions/TipButton.tsx
- packages/components/socialFeed/SocialActions/TipModal.tsx
- packages/hooks/feed/usePost.ts
- packages/utils/text.tsx
Closes #1376 
Gno network: https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L119
Other networks: https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L159
Closes #1389 
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L90
`tipAmount` was a `string` here, so the `addedAmount` addition results on a broken number displayed
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/hooks/feed/usePost.ts#L74
I used the same pattern as here: https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/utils/social-feed.ts#L123
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/so …
> fix(feed): Fix Tip action and TipModal

- go/internal/indexerhandler/feed.go
- go/pkg/feed/service.go
Closes https://github.com/TERITORI/teritori-dapp/issues/1374
> fix(feed): Properly get reactions from Posts endpoint

- packages/hooks/dao/useDAOProposals.ts
without this, if we query the proposals for a teritori dao and the gno query resolves first with nothing, the teritori query will return an empty list
> fix: dao proposals query key

- packages/components/inputs/TextInputCustom.tsx
Closes https://github.com/TERITORI/teritori-dapp/issues/1458
This PR adds a behavior present on `TextInputCustom` `"labelOutside"` but missing on `"regular"`
(The red asterix next to the label for required inputs)
___
The `"labelOutside"` variant
> fix: Show the asterix in "regular" required TextInputCustom

- packages/components/mini/SelectPicture.tsx
- packages/components/video/FeedVideosList.tsx
- packages/components/video/UploadVideoButton.tsx
- packages/components/video/UploadVideoModal.tsx
- packages/components/video/VideoCard.tsx
Change the `fontWeight` in music feed screen
---
Before:
After:
> feat: change font weight in video feed screen

- packages/screens/Feed/components/MapFeed.tsx
- packages/screens/Feed/components/MusicFeed.tsx
- packages/screens/Feed/components/VideosFeed.tsx
Give full width for all feed screens
---
Just an example for the map
Before:
After:
> fix: fullWidth for all feed screens

- assets/sidebar/side-notch.svg
- packages/components/navigation/components/SideNotch.tsx
- packages/components/navigation/components/SidebarButton.tsx
- packages/dapp-root/Root.tsx
- packages/screens/DAppStore/query/getFromFile.ts
https://github.com/TERITORI/teritori-dapp/blob/b82fc13df32c7758b96743460c1a14efc00f2618/packages/components/navigation/components/SideNotch.tsx#L10
Need that to make RAKKi yellow
> feat(rakki): Add RAKKi to sidebar

- packages/components/ImageBackgroundLogoText.tsx
- packages/components/Pagination.tsx
- packages/components/badges/PrimaryBadge.tsx
- packages/components/buttons/SecondaryButton.tsx
- packages/components/cards/FlowCard.tsx
- packages/components/footers/LegalFooter.tsx
- packages/components/inputs/AvailableNamesInput.tsx
- packages/components/inputs/SelectInput.tsx
- packages/components/inputs/TextInputCustom.tsx
- packages/components/modals/GradientModalBase.tsx
- packages/components/modals/teritoriNameService/TNSNameFinderModal.tsx
- packages/components/table/utils.ts
- packages/components/teritoriNameService/FindAName.tsx
- packages/components/teritoriNameService/MediaPreview.tsx
- packages/components/teritoriNameService/NameAndTldText.tsx
- packages/components/teritoriNameService/NameDataForm.tsx
- packages/components/teritoriNameService/NameNFT.tsx
- packages/components/teritoriNameService/NameStatus.tsx
- packages/screens/TeritoriNameService/TNSBurnNameScreen.tsx
- packages/screens/TeritoriNameService/TNSConsultNameScreen.tsx
- packages/screens/TeritoriNameService/TNSManageScreen.tsx
- packages/screens/TeritoriNameService/TNSMintNameScreen.tsx
- packages/utils/style/fonts.ts
Change `fontWeight` for all tns screens
There is an example for the `HomeScreen`:
Before:
After:
> fix: fontWeight for all tns screens

- packages/components/Menu.tsx
- packages/components/buttons/MaxButton.tsx
- packages/components/hub/MyNFTs.tsx
- packages/components/hub/WalletDashboardHeader.tsx
- packages/components/inputs/TextInputCustom.tsx
- packages/components/modals/DepositWithdrawModal.tsx
- packages/screens/WalletManager/Assets.tsx
- packages/screens/WalletManager/WalletItem.tsx
- packages/screens/WalletManager/WalletManagerScreen.tsx
- packages/screens/WalletManager/WalletsScreen.tsx
- packages/utils/style/fonts.ts
Fixed `fontWeight` and `fullWidth` for `Wallet manager` screen
- In [packages/components/inputs/TextInputCustom.tsx](https://github.com/TERITORI/teritori-dapp/compare/fix/font-weight-wallet-manager-screen?expand=1#diff-bb97de0fba5ec87bf11b47f33e384a8662ce3b259c7ebd7b15a4fbff843dfbb2) i put a text color by default (i did the same thing than here [BrandTextBase.tsx](https://github.com/TERITORI/teritori-dapp/blob/main/packages/components/BrandText/BrandTextBase.tsx#L13))
Before:
After:
- I changed just the spacing of some style props which were many lines and could fit in one line ([example](https://github.com/TERITORI/teritori-dapp/compare/fix/font-weight-wallet-manager-screen?expand=1#diff-98a8d10ae3681c28d87b68e5f3e613282cdd9df1b00659409e035343cebc5d01L28-R30) here)
For the `fullWidth` …
> fix: fontWeight and fullWidth for Wallet manager screen

- packages/components/DropdownOption.tsx
- packages/components/ImageWithTextInsert.tsx
- packages/components/SideFilters.tsx
- packages/components/badges/TertiaryBadge.tsx
- packages/components/buttons/SocialButtonSecondary.tsx
- packages/components/collections/CollectionHeader.tsx
- packages/components/collections/CollectionStat.tsx
- packages/components/nfts/NFTView.tsx
- packages/components/sorts/SortButton.tsx
- packages/screens/Marketplace/CollectionScreen.tsx
- packages/screens/Marketplace/MarketplaceScreen.tsx
- packages/screens/Marketplace/PeriodFilter.tsx
- packages/screens/Marketplace/SideCart.tsx
Change `fontWeight` and `fullWidth` on marketplace screen.
Before:
After:
> fix: fontWeight and fullWidth on marketplace screen

- packages/components/EmptyList.tsx
- packages/components/ErrorText.tsx
- packages/components/badges/TertiaryBadge.tsx
- packages/components/inputs/TextInputOutsideLabel.tsx
- packages/components/multisig/MultisigTransactions.tsx
- packages/screens/Multisig/MultisigCreateScreen.tsx
- packages/screens/Multisig/MultisigScreen.tsx
- packages/screens/Multisig/MultisigWalletDashboardScreen.tsx
- packages/screens/Multisig/components/GetStartedOption.tsx
- packages/screens/Multisig/components/MultisigFormInput.tsx
- packages/screens/Multisig/components/MultisigRightSection.tsx
- packages/screens/Multisig/components/MultisigSection.tsx
- packages/utils/style/fonts.ts
Changed `fontWeight` for all multisig screens.
Unify `fullWidth` behaviour like other screens.
Before:
After:
> fix: font weight multisig screen
